//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinIsoBurn.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinIsoBurn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You cannot cancel once after starting to erase. Eraseing media may take much time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaErase_Description {
            get {
                return ResourceManager.GetString("MediaErase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erasing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaErase_Erasing {
            get {
                return ResourceManager.GetString("MediaErase_Erasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erase the media quickly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaErase_Quick {
            get {
                return ResourceManager.GetString("MediaErase_Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erase に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaErase_Start {
            get {
                return ResourceManager.GetString("MediaErase_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rewritable media is selected. Need to erase the disc before writing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaErase_Title {
            get {
                return ResourceManager.GetString("MediaErase_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank BD-R に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_BlankBDR {
            get {
                return ResourceManager.GetString("MediaType_BlankBDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank CD-R に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_BlankCDR {
            get {
                return ResourceManager.GetString("MediaType_BlankCDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank DVD+R に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_BlankDVDPlusR {
            get {
                return ResourceManager.GetString("MediaType_BlankDVDPlusR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank DVD+RDL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_BlankDVDPlusR_DL {
            get {
                return ResourceManager.GetString("MediaType_BlankDVDPlusR_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank DVD-R に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_BlankDVDR {
            get {
                return ResourceManager.GetString("MediaType_BlankDVDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank DVD-R DL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_BlankDVDR_DL {
            get {
                return ResourceManager.GetString("MediaType_BlankDVDR_DL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DVD+RW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_DVDPlusRW {
            get {
                return ResourceManager.GetString("MediaType_DVDPlusRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DVD-RAM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_DVDRAM {
            get {
                return ResourceManager.GetString("MediaType_DVDRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DVD-ROM or recorded DVD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_DVDROM {
            get {
                return ResourceManager.GetString("MediaType_DVDROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DVD-RW に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_DVDRW {
            get {
                return ResourceManager.GetString("MediaType_DVDRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown media inserted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaType_UnknownMedia {
            get {
                return ResourceManager.GetString("MediaType_UnknownMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid response from device. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaTypeError_InvalidResponseFromDevice {
            get {
                return ResourceManager.GetString("MediaTypeError_InvalidResponseFromDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No media inserted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MediaTypeError_NoMediaInserted {
            get {
                return ResourceManager.GetString("MediaTypeError_NoMediaInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_ButtonFileSelect {
            get {
                return ResourceManager.GetString("Page1_ButtonFileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm image file compatibility に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_ButtonISOCheck {
            get {
                return ResourceManager.GetString("Page1_ButtonISOCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This image file cannot be used due to too big file size. Select another file and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_ISO_Error_FileSize {
            get {
                return ResourceManager.GetString("Page1_ISO_Error_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This image file is invalid. Confirm the file or select another file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_ISO_Error_InvalidISO {
            get {
                return ResourceManager.GetString("Page1_ISO_Error_InvalidISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This image file has no problem. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_ISO_NoProblem {
            get {
                return ResourceManager.GetString("Page1_ISO_NoProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("Page1_OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select an image file to be written に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_Title {
            get {
                return ResourceManager.GetString("Page1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select file to be written に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page1_WindowTitle {
            get {
                return ResourceManager.GetString("Page1_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media in the drive: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_MediaInTheDrive {
            get {
                return ResourceManager.GetString("Page2_MediaInTheDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close the disc after writing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_OptionClosing {
            get {
                return ResourceManager.GetString("Page2_OptionClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify the disc after writing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_OptionVerifying {
            get {
                return ResourceManager.GetString("Page2_OptionVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a drive: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_SelectDrive {
            get {
                return ResourceManager.GetString("Page2_SelectDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_SpeedMax {
            get {
                return ResourceManager.GetString("Page2_SpeedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_SpeedSuffix {
            get {
                return ResourceManager.GetString("Page2_SpeedSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Not available) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_SpeedUnavailable {
            get {
                return ResourceManager.GetString("Page2_SpeedUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported media: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_SupportedMedia {
            get {
                return ResourceManager.GetString("Page2_SupportedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a drive and set recording media to the drive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_Title {
            get {
                return ResourceManager.GetString("Page2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preaparation of drive and media に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_WindowTitle {
            get {
                return ResourceManager.GetString("Page2_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing speed: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page2_WritingSpeed {
            get {
                return ResourceManager.GetString("Page2_WritingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceling... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page3_Canceling {
            get {
                return ResourceManager.GetString("Page3_Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enough capacity is not available on this media type. Disc creation has not been completed. Please change the media type and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page3_Error_NotEnoughCapacity {
            get {
                return ResourceManager.GetString("Page3_Error_NotEnoughCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Final processing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page3_FinalProcessing {
            get {
                return ResourceManager.GetString("Page3_FinalProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time remainings:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page3_TimeRemainings {
            get {
                return ResourceManager.GetString("Page3_TimeRemainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing the file onto the disc... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page3_Title {
            get {
                return ResourceManager.GetString("Page3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page3_Verifying {
            get {
                return ResourceManager.GetString("Page3_Verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Media writing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page3_WindowTitle {
            get {
                return ResourceManager.GetString("Page3_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disc writing has been canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page4_Canceled {
            get {
                return ResourceManager.GetString("Page4_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove the disc from the drive and close the windows. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page4_Description {
            get {
                return ResourceManager.GetString("Page4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disc writing completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page4_Title {
            get {
                return ResourceManager.GetString("Page4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Page4_WindowTitle {
            get {
                return ResourceManager.GetString("Page4_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wizard_Back {
            get {
                return ResourceManager.GetString("Wizard_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wizard_Cancel {
            get {
                return ResourceManager.GetString("Wizard_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wizard_Close {
            get {
                return ResourceManager.GetString("Wizard_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wizard_Create {
            get {
                return ResourceManager.GetString("Wizard_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wizard_Next {
            get {
                return ResourceManager.GetString("Wizard_Next", resourceCulture);
            }
        }
    }
}
